### ISSUE TITLE
i am not to supports Rtl?

### ISSUE THREAD

**Issue by majdalden** [xyxyLiu/Edit-Spinner#4]
error if not supportsRtl 

`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:10:9-36
  	is also present at [com.reginald:editspinner:1.0.0] AndroidManifest.xml:14:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:5:5-38:19 to override.`

i am not to supports Rtl
how this ?

**Comment by xyxyLiu** [comment]
You can add  tools:replace="android:supportsRtl"  in your manifest to replace this attribute.
This link may be helpful: [https://developer.android.com/studio/build/manifest-merge.html#attribute_markers](https://developer.android.com/studio/build/manifest-merge.html#attribute_markers)

**Comment by MajdAldenH** [comment]
Thanks you
