### ISSUE TITLE
App is getting stop

### ISSUE THREAD

**Issue by Seyedalifathima** [xyxyLiu/Edit-Spinner#6]
I am using list instead of string array in adapter.My application getting stop by saying 
 
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListPopupWindow.setAdapter(android.widget.ListAdapter)' on a null object reference

the below is my code

implementation 'com.reginald:editspinner:1.0.0' // is added in dependency

package com.example.ind_009.sample_app;
import android.content.Context;
import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.InputType;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.reginald.editspinner.EditSpinner;
import android.view.inputmethod.InputMethodManager;
import android.widget.ListAdapter;
import android.widget.PopupWindow;
import java.util.ArrayList;
import java.util.List;
public class Second extends AppCompatActivity {

    EditSpinner ets;
   
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second);
      
        list.add("4");
        list.add("1");
        list.add("1");
        list.add("4");
        list.add("4");

        ets=new EditSpinner(Second.this);
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_dropdown_item,
                list);
        ets.setAdapter(adapter);
        ets.setOnDismissListener(new PopupWindow.OnDismissListener() {
            @Override
            public void onDismiss() {
                Log.d("Second", "mEditSpinner1 popup window dismissed!");
            }
        });

        // triggered when dropdown popup window shown
        ets.setOnShowListener(new EditSpinner.OnShowListener() {
            @Override
            public void onShow() {
                // maybe you want to hide the soft input panel when the popup window is showing.
                hideSoftInputPanel();
            }
        });

    }
    private void hideSoftInputPanel() {
        InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
        if (imm != null) {
            imm.hideSoftInputFromWindow(ets.getWindowToken(), 0);
        }
    }
}
where I am getting struck

**Comment by xyxyLiu** [comment]
FIXED
